from pathlib import Path

DEFAULT_DB_FILENAME = "monitor.db"
DEFAULT_TIMEOUT_SECONDS = 10.0
DEFAULT_CHECK_INTERVAL_SECONDS = 60
DEFAULT_USER_AGENT = "WebsiteMonitor/0.1.0"
DEFAULT_RETENTION_DAYS = 30
DEFAULT_CONSECUTIVE_FAILURES_BEFORE_ALERT = 2
DEFAULT_SSL_WARNING_DAYS = 14
DEFAULT_HTTP_METHOD = "GET"
DEFAULT_EXPECTED_STATUS = 200


def get_default_db_path() -> Path:
    return Path(__file__).resolve().parent.parent / DEFAULT_DB_FILENAME
